---

- name: Write SQL configuration
  copy:
    src: files/etc/mysql/99-roundcube.cnf
    dest: /etc/mysql/mariadb.conf.d/99-roundcube.cnf

- name: Restart mariadb
  service:
    name: mariadb
    state: restarted

- name: Create roundcube directory
  file:
    path: /etc/roundcube
    state: directory

- name: Copy managesieve config
  template:
    src: templates/roundcube/managesieve.php.j2
    dest: /etc/roundcube/managesieve.php

- name: Pull images
  docker_image:
    name: roundcube/roundcubemail:latest
    source: pull
    force_source: yes

- name: docker-compose via ansible docker_service
  docker_compose:
    project_name: "roundcube"
    definition:
      version: "3"
      services:
        roundcube:
          image: roundcube/roundcubemail:latest
          volumes:
            - /etc/roundcube/managesieve.php:/var/roundcube/config/managesieve.php
          ports:
            - 1082:80
          environment:
            - "ROUNDCUBEMAIL_DEFAULT_HOST=ssl://{{ roundcube_hostname }}"
            - "ROUNDCUBEMAIL_SMTP_SERVER=tls://{{ roundcube_hostname }}"
            - ROUNDCUBEMAIL_DEFAULT_PORT=993
            - ROUNDCUBEMAIL_PLUGINS=managesieve,password,emoticons
            - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
            - ROUNDCUBEMAIL_DB_TYPE=mysql
            - ROUNDCUBEMAIL_DB_HOST={{ phpmyadmin_hostname }}
            - ROUNDCUBEMAIL_DB_PORT=3306
            - ROUNDCUBEMAIL_DB_USER=roundcube
            - ROUNDCUBEMAIL_DB_PASSWORD=GJlSwqhUu1IkZQKivEPQL8w2
            - ROUNDCUBEMAIL_DB_NAME=roundcube
          restart: always
    state: present
    restarted: true

# apache2 setup

- name: Create directory for certificate
  file:
    path: "/etc/apache2/certs/{{ roundcube_hostname }}"
    state: directory

- name: Check if SSL certificate is present
  stat:
    path: "/etc/apache2/certs/{{ roundcube_hostname }}/fullchain.pem"
  register: letsencrypt_cert

- name: Generate temporary certificate
  command: openssl req
    -x509
    -nodes
    -days 30
    -newkey rsa:2048
    -keyout /etc/apache2/certs/"{{ roundcube_hostname }}"/privkey.pem
    -out /etc/apache2/certs/"{{ roundcube_hostname }}"/fullchain.pem
    -subj "/C=US/ST=DummyState/L=DummyTown/O=DummyCompany/OU=Software/CN=dummy-company.com"
  when: not letsencrypt_cert.stat.exists

- name: Change permission of temporary key
  file:
    path: "/etc/apache2/certs/{{ roundcube_hostname }}/privkey.pem"
    mode: u=rw,g=,o=
  when: not letsencrypt_cert.stat.exists

- name: Copy apache vhost
  template:
    src: templates/sites_available/roundcube.vhost.j2
    dest: /etc/apache2/sites-available/roundcube.vhost

- name: Enable apache vhost
  file:
    src: /etc/apache2/sites-available/roundcube.vhost
    dest: /etc/apache2/sites-enabled/roundcube.vhost
    state: link

- name: Restart apache
  service:
    name: apache2
    state: restarted

- name: Remove old APT based roundcube packages
  apt:
    name: "{{ packages }}"
    autoremove: yes
    purge: yes
    state: absent
  vars:
    packages:
      - roundcube
      - roundcube-core
      - roundcube-mysql
      - roundcube-plugins
